export const EMAIL_REGISTER_CHANGED = 'EMAIL_REGISTER_CHANGED';
export const USERNAME_REGISTER_CHANGED = 'USERNAME_REGISTER_CHANGED';
export const PASSWORD_REGISTER_CHANGED = 'PASSWORD_REGISTER_CHANGED';
export const CON_PASSWORD_REGISTER_CHANGED = 'CON_PASSWORD_REGISTER_CHANGED';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';

export const EMAIL_LOGIN_CHANGED = 'EMAIL_LOGIN_CHANGED';
export const PASSWORD_LOGIN_CHANGED = 'PASSWORD_LOGIN_CHANGED';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const NOT_LOGIN_YET = 'NOT_LOGIN_YET';


export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
export const EDIT_PROFILE_INIT = 'EDIT_PROFILE_INIT';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const USERNAME_PROFILE_CHANGED = 'USERNAME_PROFILE_CHANGED';
export const IMAGE_PROFILE_CHANGED = 'IMAGE_PROFILE_CHANGED';

